#!/usr/bin/env python3
"""gen_jamo.py -- generate real 8x8 Hangul jamo bitmap tables.

The rename that converted sungwang -> clock-out destroyed the original jamo
glyph data in korean/hangul.HC; the recovery workers left placeholder diagonal
patterns. This renders each compatibility jamo with AppleGothic at high
resolution and downscales to an 8x8 thresholded bitmap, matching the layout
the compose/stamp loop expects (draw_jamo: row byte, MSB = leftmost pixel).

Output: korean/jamo_data.HC  -- defines HANGUL_CHO[19][8], HANGUL_JUNG[21][8],
                               HANGUL_JONG[28][8]  (identical symbol names to
                               the ones hangul.HC currently defines).
Run: python3 tools/gen_jamo.py
Idempotent and deterministic (no randomness).
"""
from PIL import Image, ImageDraw, ImageFont
import sys, os

FONT = "/System/Library/Fonts/AppleGothic.ttf"
# .h so it is NOT picked up by the Makefile's korean/*.HC glob (which would
# compile it as its own TU and duplicate the symbols). hangul.HC includes it.
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "korean", "jamo_data.h")

# Explicit compatibility-jamo strings (avoids codepoint arithmetic mistakes).
CH = "ㄱㄲㄴㄷㄸㄹㅁㅂㅃㅅㅆㅇㅈㅉㅊㅋㅌㅍㅎ"              # 19 choseong
JUNG = "ㅏㅐㅑㅒㅓㅔㅕㅖㅗㅘㅙㅚㅛㅜㅝㅞㅟㅠㅡㅢㅣ"        # 21 jungseong
JONG = ""  # index 0 = blank; 1..27 from the full final-consonant set
JONG_SET = "ㄱㄲㄳㄴㄵㄶㄷㄹㄺㄻㄼㄽㄾㄿㅀㅁㅂㅄㅅㅆㅇㅈㅊㅋㅌㅍㅎ"  # 27

HIRES = 64   # render size before downscale to 8


def glyph_bitmap(ch: str) -> list:
    """Render one jamo -> 8 rows of bytes (MSB = leftmost pixel)."""
    img = Image.new("L", (HIRES, HIRES), 0)
    d = ImageDraw.Draw(img)
    try:
        f = ImageFont.truetype(FONT, HIRES)
    except OSError:
        f = ImageFont.truetype("/System/Library/Fonts/AppleSDGothicNeo.ttc", HIRES)
    bbox = d.textbbox((0, 0), ch, font=f)
    w, h = bbox[2] - bbox[0], bbox[3] - bbox[1]
    if w <= 0 or h <= 0:
        return [0] * 8
    # center the glyph in the box
    d.text(((HIRES - w) / 2 - bbox[0], (HIRES - h) / 2 - bbox[1]), ch, font=f, fill=255)
    small = img.resize((8, 8), Image.LANCZOS)
    rows = []
    for yy in range(8):
        byte = 0
        for xx in range(8):
            if small.getpixel((xx, yy)) > 100:  # threshold
                byte |= (0x80 >> xx)
        rows.append(byte)
    return rows


def render_table(name, glyphs, out):
    out.append(f"const uint8_t {name}[{len(glyphs)}][8] = {{")
    for ch in glyphs:
        rows = glyph_bitmap(ch)
        out.append("    {" + ", ".join(str(b) for b in rows) + "},")
    out.append("};")


def main():
    out = []
    out.append("/* korean/jamo_data.h -- real 8x8 jamo glyph bitmaps.")
    out.append(" * AUTO-GENERATED by tools/gen_jamo.py (AppleGothic). Do not edit by hand.")
    out.append(" * Row byte layout: MSB = leftmost pixel (matches draw_jamo). */")
    out.append("#ifndef JAMO_DATA_H")
    out.append("#define JAMO_DATA_H")
    out.append("#include <stdint.h>")
    out.append("")
    render_table("HANGUL_CHO", CH, out)
    out.append("")
    render_table("HANGUL_JUNG", JUNG, out)
    out.append("")
    # index 0 blank, then 27 final consonants
    out.append("const uint8_t HANGUL_JONG[28][8] = {")
    out.append("    {0, 0, 0, 0, 0, 0, 0, 0},")
    for ch in JONG_SET:
        rows = glyph_bitmap(ch)
        out.append("    {" + ", ".join(str(b) for b in rows) + "},")
    out.append("};")
    out.append("")
    out.append("#endif /* JAMO_DATA_H */")
    out.append("")

    with open(OUT, "w") as f:
        f.write("\n".join(out))
    print(f"wrote {os.path.normpath(OUT)}")

    # sanity: render composed syllables to a test sheet for eyeballing
    test = Image.new("L", (8 * 8 * 12, 8 * 2 + 30), 0)
    td = ImageDraw.Draw(test)
    for i, s in enumerate(["퇴근", "성광", "정보", "기술", "김대리", "사장", "야근", "커피", "주인", "사직", "월요일", "책임"]):
        try:
            f = ImageFont.truetype(FONT, 8)
        except OSError:
            f = ImageFont.truetype("/System/Library/Fonts/AppleSDGothicNeo.ttc", 8)
        td.text((i * 21, 2), s, font=f, fill=255)
    test = test.resize((test.width * 3, test.height * 3), Image.NEAREST)
    test.save("/tmp/jamo_sheet.png")
    print("wrote /tmp/jamo_sheet.png (renderer check image)")


if __name__ == "__main__":
    main()
