#!/usr/bin/env python3
"""gen_glyphs.py -- generate real 16x16 Hangul syllable glyphs for the game.

The jamo-compose path (hangul_compose) can only produce legible text at
8px and up if the jamo bitmaps are high quality; at 8px it self-destructs.
Instead we rasterize each syllable the game actually uses with the system
Korean font into a 16x16 bitmap and hand the renderer an atlas to blit
directly. Unknown syllables fall back to hangul_compose.

Scans content/, game/, narrative/, render/, tools/, include/, core/ and the
README for every distinct Hangul syllable, renders each with AppleGothic at
high res, thresholds to 16x16, and emits korean/syllable_data.h as two
parallel arrays keyed by syllable codepoint (sorted ascending for bsearch).

Output: korean/syllable_data.h   (auto-generated; do not edit by hand)
Run:    python3 tools/gen_glyphs.py
"""
import os, sys
from PIL import Image, ImageDraw, ImageFont

FONT = "/System/Library/Fonts/AppleGothic.ttf"
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "korean", "syllable_data.h")
HIRES = 48
CELL = 16

ROOT = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
SCAN_DIRS = ["content", "game", "narrative", "render", "tools", "include", "core", "korean"]
SCAN_FILES = ["README.md"]
EXT = (".HC", ".h", ".ssc", ".md")


def collect() -> set:
    syl = set()

    def scan_file(path):
        try:
            t = open(path, encoding="utf-8").read()
        except (OSError, UnicodeDecodeError):
            return
        for ch in t:
            if "\uAC00" <= ch <= "\uD7A3":
                syl.add(ch)

    for d in SCAN_DIRS:
        p = os.path.join(ROOT, d)
        if not os.path.isdir(p):
            continue
        for root, _, files in os.walk(p):
            if ".git" in root or "assets" in root:
                continue
            for f in files:
                if f.endswith(EXT):
                    scan_file(os.path.join(root, f))
    for f in SCAN_FILES:
        scan_file(os.path.join(ROOT, f))
    return syl


def render(ch: str) -> list:
    img = Image.new("L", (HIRES, HIRES), 0)
    d = ImageDraw.Draw(img)
    try:
        f = ImageFont.truetype(FONT, HIRES)
    except OSError:
        f = ImageFont.truetype("/System/Library/Fonts/AppleSDGothicNeo.ttc", HIRES)
    bbox = d.textbbox((0, 0), ch, font=f)
    w, h = bbox[2] - bbox[0], bbox[3] - bbox[1]
    if w <= 0 or h <= 0:
        return [0] * (CELL * CELL)
    d.text(((HIRES - w) / 2 - bbox[0], (HIRES - h) / 2 - bbox[1]), ch, font=f, fill=255)
    small = img.resize((CELL, CELL), Image.LANCZOS)
    cells = []
    for yy in range(CELL):
        for xx in range(CELL):
            cells.append(1 if small.getpixel((xx, yy)) > 90 else 0)
    return cells


def main():
    syl = sorted(collect())
    if not syl:
        print("no syllables found")
        return
    out = []
    out.append("/* korean/syllable_data.h -- 16x16 Hangul glyph atlas.")
    out.append(" * AUTO-GENERATED by tools/gen_glyphs.py (AppleGothic). Do not edit by hand.")
    out.append(" * Codepoints sorted ascending; pairs match by index. 1 byte per pixel (0/1). */")
    out.append("#ifndef SYLLABLE_DATA_H")
    out.append("#define SYLLABLE_DATA_H")
    out.append("#include <stdint.h>")
    out.append("")
    out.append(f"#define SYL_N {len(syl)}")
    out.append("")
    out.append("static const uint16_t SYL_CP[SYL_N] = {")
    for i in range(0, len(syl), 16):
        chunk = syl[i:i + 16]
        out.append("    " + " ".join(f"0x{ord(c):04X}," for c in chunk))
    out.append("};")
    out.append("")
    out.append("static const uint8_t SYL_PIX[SYL_N][%d] = {" % (CELL * CELL))
    for c in syl:
        cells = render(c)
        out.append("    /* %s */ {%s}," % (c, ",".join(str(v) for v in cells)))
    out.append("};")
    out.append("")
    out.append("#endif /* SYLLABLE_DATA_H */")
    out.append("")

    with open(OUT, "w") as f:
        f.write("\n".join(out))
    print(f"wrote {os.path.normpath(OUT)} with {len(syl)} syllables")


if __name__ == "__main__":
    main()
